export const PRODUCTS = [
    {
      id: 1,
      productName: "Stainless Steel Cookware Set",
      price: 149.99,
      productImage: "https://source.unsplash.com/400x400/?Stainless-Steel-Cookware-Set",
      categoryId: 1,
    },
    {
      id: 2,
      productName: "Kitchen Knife Set",
      price: 69.99,
      productImage: "https://source.unsplash.com/400x400/?Kitchen-knife",
      categoryId: 1,
    },
    {
      id: 3,
      productName: "Coffee Machine",
      price: 99.99,
      productImage: "https://source.unsplash.com/400x400/?Coffee-machine",
      categoryId: 1,
    },
    {
      id: 4,
      productName: "Blender",
      price: 79.99,
      productImage: "https://source.unsplash.com/400x400/?food-Blender",
      categoryId: 1,
    },
    {
      id: 5,
      productName: "Toaster",
      price: 39.99,
      productImage: "https://source.unsplash.com/400x400/?toaster",
      categoryId: 1,
    },
    {
      id: 6,
      productName: "Kitchen Scale",
      price: 24.99,
      productImage: "https://source.unsplash.com/400x400/?kitchen-scale",
      categoryId: 1,
    },
    {
      id: 7,
      productName: "Food Processor",
      price: 129.99,
      productImage: "https://source.unsplash.com/400x400/?food-processor",
      categoryId: 1,
    },
    {
      id: 8,
      productName: "Digital Thermometer",
      price: 19.99,
      productImage: "https://source.unsplash.com/400x400/?digital-thermometer",
      categoryId: 1,
    },
    {
      id: 9,
      productName: "Spice Rack Organizer",
      price: 29.99,
      productImage: "https://source.unsplash.com/400x400/?spice-rack",
      categoryId: 1,
    },
    {
      id: 10,
      productName: "Stand Mixer",
      price: 199.99,
      productImage: "https://source.unsplash.com/400x400/?stand-mixer",
      categoryId: 1,
    },

      {
        id: 11,
        productName: "Outdoor Patio Furniture Set",
        price: 299.99,
        productImage: "https://example.com/patio-furniture.jpg",
        categoryId: 2,
      },
      {
        id: 12,
        productName: "Lawn Mower",
        price: 149.99,
        productImage: "https://example.com/lawn-mower.jpg",
        categoryId: 2,
      },
      {
        id: 13,
        productName: "Garden Hose and Nozzle Set",
        price: 39.99,
        productImage: "https://example.com/garden-hose.jpg",
        categoryId: 2,
      },
      {
        id: 14,
        productName: "Solar-Powered Outdoor Lights",
        price: 24.99,
        productImage: "https://example.com/solar-lights.jpg",
        categoryId: 2,
      },
      {
        id: 15,
        productName: "Garden Shed",
        price: 199.99,
        productImage: "https://example.com/garden-shed.jpg",
        categoryId: 2,
      },
      {
        id: 16,
        productName: "Outdoor Umbrella",
        price: 49.99,
        productImage: "https://example.com/outdoor-umbrella.jpg",
        categoryId: 2,
      },
      {
        id: 17,
        productName: "Gardening Tools Set",
        price: 34.99,
        productImage: "https://example.com/gardening-tools.jpg",
        categoryId: 2,
      },
      {
        id: 18,
        productName: "Bird Feeder",
        price: 14.99,
        productImage: "https://example.com/bird-feeder.jpg",
        categoryId: 2,
      },
      {
        id: 19,
        productName: "Compost Bin",
        price: 29.99,
        productImage: "https://example.com/compost-bin.jpg",
        categoryId: 2,
      },
      {
        id: 20,
        productName: "Garden Hammock",
        price: 79.99,
        productImage: "https://example.com/garden-hammock.jpg",
        categoryId: 2,
      },

      {
        id: 21,
        productName: "Pet Bed",
        price: 49.99,
        productImage: "https://example.com/pet-bed.jpg",
        categoryId: 3,
      },
      {
        id: 22,
        productName: "Automatic Pet Feeder",
        price: 39.99,
        productImage: "https://example.com/pet-feeder.jpg",
        categoryId: 3,
      },
      {
        id: 23,
        productName: "Cat Scratching Post",
        price: 29.99,
        productImage: "https://example.com/cat-scratcher.jpg",
        categoryId: 3,
      },
      {
        id: 24,
        productName: "Dog Chew Toys Set",
        price: 19.99,
        productImage: "https://example.com/dog-toys.jpg",
        categoryId: 3,
      },
      {
        id: 25,
        productName: "Pet Grooming Kit",
        price: 34.99,
        productImage: "https://example.com/pet-grooming-kit.jpg",
        categoryId: 3,
      },
      {
        id: 26,
        productName: "Collapsible Pet Carrier",
        price: 59.99,
        productImage: "https://example.com/pet-carrier.jpg",
        categoryId: 3,
      },
      {
        id: 27,
        productName: "Fish Tank with LED Lights",
        price: 89.99,
        productImage: "https://example.com/fish-tank.jpg",
        categoryId: 3,
      },
      {
        id: 28,
        productName: "Reptile Heat Lamp",
        price: 24.99,
        productImage: "https://example.com/reptile-lamp.jpg",
        categoryId: 3,
      },
      {
        id: 29,
        productName: "Small Animal Cage",
        price: 44.99,
        productImage: "https://example.com/small-animal-cage.jpg",
        categoryId: 3,
      },
      {
        id: 30,
        productName: "Pet GPS Tracker",
        price: 79.99,
        productImage: "https://example.com/pet-tracker.jpg",
        categoryId: 3,
      },

      {
        id: 31,
        productName: "Men's Denim Jeans",
        price: 49.99,
        productImage: "https://example.com/mens-jeans.jpg",
        categoryId: 4,
      },
      {
        id: 32,
        productName: "Women's Leather Jacket",
        price: 89.99,
        productImage: "https://example.com/womens-jacket.jpg",
        categoryId: 4,
      },
      {
        id: 33,
        productName: "Kid's Cartoon T-Shirt",
        price: 19.99,
        productImage: "https://example.com/kids-tshirt.jpg",
        categoryId: 4,
      },
      {
        id: 34,
        productName: "Sports Hoodie",
        price: 34.99,
        productImage: "https://example.com/sports-hoodie.jpg",
        categoryId: 4,
      },
      {
        id: 35,
        productName: "Women's Summer Dress",
        price: 39.99,
        productImage: "https://example.com/womens-dress.jpg",
        categoryId: 4,
      },
      {
        id: 36,
        productName: "Men's Formal Shirt",
        price: 29.99,
        productImage: "https://example.com/mens-shirt.jpg",
        categoryId: 4,
      },
      {
        id: 37,
        productName: "Winter Scarf",
        price: 14.99,
        productImage: "https://example.com/winter-scarf.jpg",
        categoryId: 4,
      },
      {
        id: 38,
        productName: "Running Shoes",
        price: 54.99,
        productImage: "https://example.com/running-shoes.jpg",
        categoryId: 4,
      },
      {
        id: 39,
        productName: "Casual Sneakers",
        price: 24.99,
        productImage: "https://example.com/casual-sneakers.jpg",
        categoryId: 4,
      },
      {
        id: 40,
        productName: "Unisex Beanie Hat",
        price: 9.99,
        productImage: "https://example.com/beanie-hat.jpg",
        categoryId: 4,
      },

      {
        id: 41,
        productName: "Building Blocks Set",
        price: 29.99,
        productImage: "https://example.com/building-blocks.jpg",
        categoryId: 5,
      },
      {
        id: 42,
        productName: "Dollhouse with Furniture",
        price: 49.99,
        productImage: "https://example.com/dollhouse.jpg",
        categoryId: 5,
      },
      {
        id: 43,
        productName: "Remote Control Car",
        price: 24.99,
        productImage: "https://example.com/rc-car.jpg",
        categoryId: 5,
      },
      {
        id: 44,
        productName: "Educational Puzzle Set",
        price: 19.99,
        productImage: "https://example.com/puzzle-set.jpg",
        categoryId: 5,
      },
      {
        id: 45,
        productName: "Art and Craft Kit",
        price: 14.99,
        productImage: "https://example.com/art-kit.jpg",
        categoryId: 5,
      },
      {
        id: 46,
        productName: "Plush Stuffed Animals",
        price: 34.99,
        productImage: "https://example.com/plush-animals.jpg",
        categoryId: 5,
      },
      {
        id: 47,
        productName: "Board Games Bundle",
        price: 39.99,
        productImage: "https://example.com/board-games.jpg",
        categoryId: 5,
      },
      {
        id: 48,
        productName: "Interactive Learning Tablet",
        price: 59.99,
        productImage: "https://example.com/learning-tablet.jpg",
        categoryId: 5,
      },
      {
        id: 49,
        productName: "Outdoor Playground Set",
        price: 149.99,
        productImage: "https://example.com/playground-set.jpg",
        categoryId: 5,
      },
      {
        id: 50,
        productName: "Toy Kitchen Playset",
        price: 69.99,
        productImage: "https://example.com/toy-kitchen.jpg",
        categoryId: 5,
      },

      {
        id: 51,
        productName: "Desk Organizer Set",
        price: 19.99,
        productImage: "https://example.com/desk-organizer.jpg",
        categoryId: 6,
      },
      {
        id: 52,
        productName: "Ergonomic Office Chair",
        price: 129.99,
        productImage: "https://example.com/office-chair.jpg",
        categoryId: 6,
      },
      {
        id: 53,
        productName: "Wireless Keyboard and Mouse Combo",
        price: 49.99,
        productImage: "https://example.com/keyboard-mouse.jpg",
        categoryId: 6,
      },
      {
        id: 54,
        productName: "Document Scanner",
        price: 89.99,
        productImage: "https://example.com/document-scanner.jpg",
        categoryId: 6,
      },
      {
        id: 55,
        productName: "Desk Lamp with USB Charger",
        price: 29.99,
        productImage: "https://example.com/desk-lamp.jpg",
        categoryId: 6,
      },
      {
        id: 56,
        productName: "Whiteboard and Marker Set",
        price: 34.99,
        productImage: "https://example.com/whiteboard.jpg",
        categoryId: 6,
      },
      {
        id: 57,
        productName: "Laptop Stand",
        price: 24.99,
        productImage: "https://example.com/laptop-stand.jpg",
        categoryId: 6,
      },
      {
        id: 58,
        productName: "Conference Room Table",
        price: 149.99,
        productImage: "https://example.com/conference-table.jpg",
        categoryId: 6,
      },
      {
        id: 59,
        productName: "Noise-Canceling Headphones",
        price: 79.99,
        productImage: "https://example.com/headphones.jpg",
        categoryId: 6,
      },
      {
        id: 60,
        productName: "Desk Plant",
        price: 14.99,
        productImage: "https://example.com/desk-plant.jpg",
        categoryId: 6,
      },

      {
        id: 61,
        productName: "Car Seat Covers Set",
        price: 39.99,
        productImage: "https://example.com/car-seat-covers.jpg",
        categoryId: 7,
      },
      {
        id: 62,
        productName: "Car Phone Mount",
        price: 14.99,
        productImage: "https://example.com/car-phone-mount.jpg",
        categoryId: 7,
      },
      {
        id: 63,
        productName: "Car Care Kit",
        price: 29.99,
        productImage: "https://example.com/car-care-kit.jpg",
        categoryId: 7,
      },
      {
        id: 64,
        productName: "Portable Tire Inflator",
        price: 24.99,
        productImage: "https://example.com/tire-inflator.jpg",
        categoryId: 7,
      },
      {
        id: 65,
        productName: "Car Vacuum Cleaner",
        price: 34.99,
        productImage: "https://example.com/car-vacuum.jpg",
        categoryId: 7,
      },
      {
        id: 66,
        productName: "Car Air Freshener",
        price: 9.99,
        productImage: "https://example.com/car-air-freshener.jpg",
        categoryId: 7,
      },
      {
        id: 67,
        productName: "Dashboard Camera",
        price: 69.99,
        productImage: "https://example.com/dashboard-camera.jpg",
        categoryId: 7,
      },
      {
        id: 68,
        productName: "Car Floor Mats Set",
        price: 49.99,
        productImage: "https://example.com/car-floor-mats.jpg",
        categoryId: 7,
      },
      {
        id: 69,
        productName: "Jump Starter Kit",
        price: 79.99,
        productImage: "https://example.com/jump-starter.jpg",
        categoryId: 7,
      },
      {
        id: 70,
        productName: "Car Wash Kit",
        price: 19.99,
        productImage: "https://example.com/car-wash-kit.jpg",
        categoryId: 7,
      },

      {
        id: 71,
        productName: "Christmas Tree Decoration Set",
        price: 29.99,
        productImage: "https://example.com/christmas-tree-decorations.jpg",
        categoryId: 8,
      },
      {
        id: 72,
        productName: "LED String Lights",
        price: 19.99,
        productImage: "https://example.com/led-string-lights.jpg",
        categoryId: 8,
      },
      {
        id: 73,
        productName: "Santa Claus Figurine",
        price: 14.99,
        productImage: "https://example.com/santa-claus-figurine.jpg",
        categoryId: 8,
      },
      {
        id: 74,
        productName: "Christmas Wreath",
        price: 24.99,
        productImage: "https://example.com/christmas-wreath.jpg",
        categoryId: 8,
      },
      {
        id: 75,
        productName: "Holiday Pillow Covers Set",
        price: 12.99,
        productImage: "https://example.com/holiday-pillow-covers.jpg",
        categoryId: 8,
      },
      {
        id: 76,
        productName: "Christmas Stockings",
        price: 9.99,
        productImage: "https://example.com/christmas-stockings.jpg",
        categoryId: 8,
      },
      {
        id: 77,
        productName: "Festive Dinnerware Set",
        price: 39.99,
        productImage: "https://example.com/festive-dinnerware.jpg",
        categoryId: 8,
      },
      {
        id: 78,
        productName: "Holiday Table Runner",
        price: 14.99,
        productImage: "https://example.com/holiday-table-runner.jpg",
        categoryId: 8,
      },
      {
        id: 79,
        productName: "Christmas Tree Skirt",
        price: 19.99,
        productImage: "https://example.com/christmas-tree-skirt.jpg",
        categoryId: 8,
      },
      {
        id: 80,
        productName: "Snowman Figurine",
        price: 17.99,
        productImage: "https://example.com/snowman-figurine.jpg",
        categoryId: 8,
      },

      {
        id: 81,
        productName: "Smart Home Security Camera",
        price: 59.99,
        productImage: "https://example.com/security-camera.jpg",
        categoryId: 9,
      },
      {
        id: 82,
        productName: "Foldable Electric Scooter",
        price: 249.99,
        productImage: "https://example.com/electric-scooter.jpg",
        categoryId: 9,
      },
      {
        id: 83,
        productName: "Robot Vacuum Cleaner",
        price: 129.99,
        productImage: "https://example.com/robot-vacuum.jpg",
        categoryId: 9,
      },
      {
        id: 84,
        productName: "Bluetooth Fitness Tracker",
        price: 39.99,
        productImage: "https://example.com/fitness-tracker.jpg",
        categoryId: 9,
      },
      {
        id: 85,
        productName: "Digital Drawing Tablet",
        price: 79.99,
        productImage: "https://example.com/drawing-tablet.jpg",
        categoryId: 9,
      },
      {
        id: 86,
        productName: "Portable Camping Grill",
        price: 49.99,
        productImage: "https://example.com/camping-grill.jpg",
        categoryId: 9,
      },
      {
        id: 87,
        productName: "Wireless Gaming Mouse",
        price: 34.99,
        productImage: "https://example.com/gaming-mouse.jpg",
        categoryId: 9,
      },
      {
        id: 88,
        productName: "Smart Thermostatic Mug",
        price: 29.99,
        productImage: "https://example.com/thermostatic-mug.jpg",
        categoryId: 9,
      },
      {
        id: 89,
        productName: "Vintage Vinyl Record Player",
        price: 99.99,
        productImage: "https://example.com/record-player.jpg",
        categoryId: 9,
      },
      {
        id: 90,
        productName: "Portable Bluetooth Projector",
        price: 129.99,
        productImage: "https://example.com/bluetooth-projector.jpg",
        categoryId: 9,
      },


    ];

    

  
  
  






